version: '2.1'
services:
  python-rest:
    image: '13515135.registr.amazon.com/myjar-test:latest'
    container_name: python-rest
    restart: unless-stopped
    network_mode: host
    environment:
      MYSQL_DATABASE_USERNAME: root
      MYSQL_DATABASE_PASSWORD: dbvi2837g13
      MYSQL_DATABASE_DB: myjardb
      MYSQL_DATABASE_HOST: 8186551.hffh.aws.amazon.com