---
- hosts: localhost
  gather_facts: no
  vars:
    ecr_url: 13515135.registr.amazon.com
    ecr_repo_name: myjar-test
    db_user: root
    db_password: dbvi2837g13
    db_name: myjardb
    rds_db_host: 8186551.hffh.aws.amazon.com
  tasks:
    - name: create temporary file
      tempfile:
        state: file
        suffix: ec2
      register: ec2tmpfile

    - debug:
        var: ec2tmpfile

    - name: template
      template:
        src: roles/deploy_ec2/templates/docker-compose.yml.j2
        dest: "{{ ec2tmpfile['path'] }}"

    - name: file content
      shell: "cat {{ ec2tmpfile['path'] }}"
      register: shell_out
      
    - debug:
        msg: "{{ shell_out['stdout'] | b64encode }}"