---
- name: "Install required package (mysql)"
  package:
    name: "mysql55"
    state: present

- name: |
    "Access the RDS from the instances.
    "mysql://{{ db_user }}:{{ db_password }}@{{ rds_db_host }}/{{ rds_db_name }}"
    "It will return a result with the users."
  shell: "mysql -u{{ db_user }} -p{{ db_password }} -h {{ rds_db_host }} {{ rds_db_name }} {{ db_query }}"
  register: test_result

- name: "Debug result"
  debug:
    var: test_result

- name: "Remove unnecessary package (mysql)"
  package:
    name: "mysql55"
    state: absent