---
aws_access_key: put-here-your-access-key
aws_secret_key: put-here-your-secret-key
aws_region: us-east-1
project_name: ansible-aws-asg
app_git_repo: https://github.com/username/repo.git
db_name: dbtest
db_user: root
db_password: password
db_instance_class: db.t2.micro