---
- name: "Create a new ec2 key pair"
  ec2_key:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
    name: "{{ project_name }}"
    state: "present"
  register: key_pair

- name: "Make sure that files dir exist"
  file:
    path: "files/"
    state: "directory"
  when: key_pair['changed']

- name: "Copy private key content to a local file"
  copy:
    content: "{{ key_pair['key']['private_key'] }}"
    dest: "files/{{ project_name }}.pem"
    mode: 0400
  when: key_pair['changed']