---
- name: "Get docker containers"
  shell: "docker ps -a --format {% raw %}'{{.ID}};{{.Names}};{{.Image}};{{.Status}}'{% endraw %}"
  register: docker_ps

- name: "debug"
  debug:
    var: docker_ps

- name: |
    "Try to access the api using internet. http://{{ ansible_host }}:5000/users"
    "It should fail, but the error will ignored because it expected."
  uri:
    url: "http://{{ ansible_host }}:5000/users"
    return_content: yes
  ignore_errors: true
  register: uri_result
  delegate_to: localhost
  become: false

- name: "debug"
  debug:
    var: uri_result

- name: |
    "Try to access the api using from the instance. http://{{ ec2_private_ip_address }}:5000/users"
    "It will return a result"
  uri:
    url: "http://{{ ec2_private_ip_address }}:5000/users"
    return_content: yes
  register: uri_result

- name: "debug"
  debug:
    var: uri_result