---
- name: Get docker containers
  shell: "docker ps -a --format {% raw %}'{{.ID}};{{.Names}};{{.Image}};{{.Status}}'{% endraw %}"
  register: docker_ps

- name: debug
  debug:
    var: docker_ps

- name: URL
  shell: "curl http://{{ ec2_private_ip_address }}:5000/users"
  register: url

- name: debug
  debug:
    var: url