---
- name: "Clean ECR repository first"
  aws_ecr_clean:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
    repository_name: "{{ project_name }}"

- name: "Remove ECR stack"
  cloudformation:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
    stack_name: "{{ project_name }}-ecr"
    state: "absent"