---
- name: create a cloudformation stack
  cloudformation:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    stack_name: "{{ project_name }}-vpc"
    state: "present"
    region: "us-east-1"
    template: "roles/deploy_vpc/files/vpc.json"
    template_parameters:
      TagProject: "{{ project_name }}"
      VpcCidrBlock: "10.10.0.0/16"
      Subnet1CidrBlock: "10.10.1.0/24"
      Subnet2CidrBlock: "10.10.2.0/24"
      Subnet3CidrBlock: "10.10.3.0/24"
    tags:
      Stack: "{{ project_name }}-vpc"
      Project: "{{ project_name }}"