---
- name: Set VPC stack name
  set_fact:
    vpc_stack_name: "{{ project_name }}-vpc"

- name: Deploy a VPC stack
  cloudformation:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
    stack_name: "{{ vpc_stack_name }}"
    state: "present"
    template: "roles/deploy_vpc/files/vpc.json"
    template_parameters:
      TagProject: "{{ project_name }}"
      VpcCidrBlock: "10.10.0.0/16"
      Subnet1CidrBlock: "10.10.1.0/24"
      Subnet2CidrBlock: "10.10.2.0/24"
      Subnet3CidrBlock: "10.10.3.0/24"
    tags:
      Stack: "{{ vpc_stack_name }}"
      Project: "{{ project_name }}"

- name: Get VPC stack facts
  cloudformation_facts:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
    stack_name: "{{ vpc_stack_name }}"

- name: Set variables with cloudformation output
  set_fact:
    vpc_id: "{{ ansible_facts['cloudformation'][vpc_stack_name]['stack_outputs']['VpcId'] }}"
    subnet1_id: "{{ ansible_facts['cloudformation'][vpc_stack_name]['stack_outputs']['Subnet1Id'] }}"
    subnet2_id: "{{ ansible_facts['cloudformation'][vpc_stack_name]['stack_outputs']['Subnet2Id'] }}"
    subnet3_id: "{{ ansible_facts['cloudformation'][vpc_stack_name]['stack_outputs']['Subnet3Id'] }}"