---
- name: Create a new ec2 key pair
  ec2_key:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    name: "{{ project_name }}"
    state: "present"
    region: "{{ aws_region }}"
  register: key_pair

- name: debug
  debug:
    var: key_pair